import os
from uuid import uuid4

import pytest

from src.database.db import (
    POSTGRES_MIGRATIONS_PATH,
    _postgres_query,
    discover_migrations,
    initialize_database,
    migration_status,
)
from src.database.finance_service import FinanceService
from src.security.auth_service import AuthService


def test_qmark_conversion_preserves_quoted_question_marks():
    query = "SELECT '?' AS literal, name FROM users WHERE id = ? AND name = 'it''s?'"

    assert _postgres_query(query) == (
        "SELECT '?' AS literal, name FROM users WHERE id = %s AND name = 'it''s?'"
    )


def test_postgres_migrations_use_portable_schema_types():
    migrations = discover_migrations(POSTGRES_MIGRATIONS_PATH)
    sql = "\n".join(migration.sql for migration in migrations)

    assert [migration.version for migration in migrations] == [1, 2]
    assert "AUTOINCREMENT" not in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "NUMERIC(20, 2)" in sql
    assert "TIMESTAMPTZ" in sql


@pytest.mark.skipif(
    not os.getenv("TEST_POSTGRES_URL"),
    reason="TEST_POSTGRES_URL is required for PostgreSQL integration testing.",
)
def test_finance_and_auth_services_run_on_postgres(monkeypatch):
    database_url = os.environ["TEST_POSTGRES_URL"]
    monkeypatch.setenv("FINANCE_DATABASE_URL", database_url)
    initialize_database()
    service = FinanceService()
    auth_service = AuthService()

    registered = auth_service.register(
        "Postgres User",
        f"postgres-{uuid4().hex}@example.com",
        "postgres-test-password",
        account_name="Postgres Bank",
    )
    account_id = service.get_accounts(registered["user_id"])[0][0]
    service.add_transaction(
        registered["user_id"],
        account_id,
        None,
        "income",
        12500.50,
        "Salary",
        "2026-08-15",
    )

    assert service.get_total_income(registered["user_id"]) == 12500.50
    assert auth_service.authenticate_access_token(registered["access_token"]) == registered["user_id"]
    refreshed = auth_service.refresh(registered["refresh_token"])
    assert auth_service.authenticate_access_token(refreshed["access_token"]) == registered["user_id"]
    assert migration_status()["backend"] == "postgresql"
