ALTER TABLE recurring_transactions ADD COLUMN schedule_kind TEXT NOT NULL
    DEFAULT 'standard' CHECK(schedule_kind IN ('standard', 'loan_emi'));
ALTER TABLE recurring_transactions ADD COLUMN loan_type TEXT
    CHECK(loan_type IS NULL OR loan_type IN ('home', 'car', 'personal', 'education', 'other'));
ALTER TABLE recurring_transactions ADD COLUMN lender TEXT;

CREATE TABLE investment_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    investment_type TEXT NOT NULL CHECK(investment_type IN (
        'mutual_fund_sip', 'lic', 'rd', 'fd', 'other'
    )),
    name TEXT NOT NULL,
    provider TEXT,
    contribution_amount NUMERIC(20, 2) NOT NULL CHECK(contribution_amount > 0),
    frequency TEXT NOT NULL CHECK(frequency IN (
        'one_time', 'daily', 'weekly', 'monthly', 'quarterly', 'yearly'
    )),
    interval_count INTEGER NOT NULL DEFAULT 1 CHECK(interval_count > 0),
    next_date DATE NOT NULL,
    maturity_date DATE,
    total_contributed NUMERIC(20, 2) NOT NULL DEFAULT 0 CHECK(total_contributed >= 0),
    current_value NUMERIC(20, 2) NOT NULL DEFAULT 0 CHECK(current_value >= 0),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK(status IN ('active', 'paused', 'completed')),
    last_contribution_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE TABLE investment_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    amount NUMERIC(20, 2) NOT NULL CHECK(amount > 0),
    contribution_date DATE NOT NULL,
    scheduled_for DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (investment_id) REFERENCES investment_plans(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE UNIQUE INDEX investment_scheduled_contribution
    ON investment_contributions(investment_id, scheduled_for)
    WHERE scheduled_for IS NOT NULL;
CREATE INDEX investment_plans_due
    ON investment_plans(user_id, status, next_date);

ALTER TABLE notifications DROP CONSTRAINT notifications_notification_type_check;
ALTER TABLE notifications ADD CHECK(notification_type IN (
    'budget_warning', 'budget_exceeded', 'goal_completed',
    'recurring_generated', 'import_completed', 'emi_generated',
    'investment_generated', 'investment_maturity'
));
